import React, { useState } from 'react';
import axios from 'axios';
import './Quiz.css';

const Quiz = () => {
  const [answers, setAnswers] = useState({});
    const [pets, setPets] = useState([]);

      const handleSubmit = async (e) => {
          e.preventDefault();
              
                  // Replace with real Petfinder API key
                      const PETFINDER_KEY = 'your-api-key';
                          
                              try {
                                    const { data } = await axios.get(
                                            'https://api.petfinder.com/v2/animals?type=dog&location=90210',
                                                    { headers: { Authorization: `Bearer ${PETFINDER_KEY}` } }
                                                          );
                                                                setPets(data.animals);
                                                                    } catch (error) {
                                                                          console.error('Failed to fetch pets:', error);
                                                                              }
                                                                                };

                                                                                  return (
                                                                                      <div className="quiz">
                                                                                            <form onSubmit={handleSubmit}>
                                                                                                    <h1>🐾 Find Your Perfect Rescue Dog</h1>
                                                                                                            
                                                                                                                    <div className="question">
                                                                                                                              <p>Where do you live?</p>
                                                                                                                                        <label>
                                                                                                                                                    <input 
                                                                                                                                                                  type="radio" 
                                                                                                                                                                                name="home"
                                                                                                                                                                                              onChange={() => setAnswers({...answers, home: 'apartment'})}
                                                                                                                                                                                                          />
                                                                                                                                                                                                                      Apartment
                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                          <label>
                                                                                                                                                                                                                                                      <input 
                                                                                                                                                                                                                                                                    type="radio" 
                                                                                                                                                                                                                                                                                  name="home" 
                                                                                                                                                                                                                                                                                                onChange={() => setAnswers({...answers, home: 'house'})}
                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                        House
                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                  <button type="submit">Find Matches</button>
                                                                                                                                                                                                                                                                                                                                                        </form>

                                                                                                                                                                                                                                                                                                                                                              <div className="pet-grid">
                                                                                                                                                                                                                                                                                                                                                                      {pets.map(pet => (
                                                                                                                                                                                                                                                                                                                                                                                <div key={pet.id} className="pet-card">
                                                                                                                                                                                                                                                                                                                                                                                            <img 
                                                                                                                                                                                                                                                                                                                                                                                                          src={pet.photos[0]?.medium || 'placeholder-dog.jpg'} 
                                                                                                                                                                                                                                                                                                                                                                                                                        alt={pet.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>{pet.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>{pet.breeds.primary}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href={pet.url} target="_blank">Adopt Me</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default Quiz;